---
version: 2.1
jobs:
  build:
    working_directory: ~/ansible-role-passenger-apache
    docker:
      - image: cimg/python:3.12.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: pipenv install --dev
      - setup_remote_docker
      - run: sudo dnf makecache; sudo dnf install rsync
      - run:
          name: Molecule
          command: pipenv run molecule test
