version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: Molecule
          command: pipenv run molecule test
