---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "rockylinux:9"
    capabilities:
      - SYS_ADMIN
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
verifier:
  name: testinfra
