---
name: "Lint and Test"

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      
      - name: Install pipenv
        run: pip install pipenv
      
      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-
      
      - name: Install dependencies
        run: pipenv install --dev
        env:
          PIPENV_VENV_IN_PROJECT: true
      
      - name: Install rsync
        run: sudo apt update && sudo apt install -y rsync
      
      - name: Run Molecule tests
        run: pipenv run molecule test
