---
name: "Molecule Test"

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}

permissions:
  contents: read # access to check out code and install dependencies

jobs:
  molecule:
    runs-on: [ self-hosted,systemd-runner ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        
      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Install rsync
        run: sudo apt update && sudo apt install -y rsync
      
      - name: Run Molecule tests
        run: pipenv run molecule test
