---
name: "Molecule Test"

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  molecule:
    runs-on: [ self-hosted, systemd-runner ]
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [ 3.12 ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: kishaningithub/setup-python-amazon-linux@v1
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pipenv'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Install rsync
        run: sudo dnf install -y rsync;

      - name: Run Molecule tests
        run: pipenv run molecule test
